FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine AS build

WORKDIR /app

#copy the code in
COPY ./TbspRpgApi /app
COPY ./TbspRpgDataLayer /TbspRpgDataLayer
COPY ./TbspRpgSettings /TbspRpgSettings
COPY ./TbspRpgProcessor /TbspRpgProcessor

#build the site
RUN dotnet restore

#publish
RUN dotnet publish -c Release -o out

#make slimmed down image
FROM mcr.microsoft.com/dotnet/aspnet:6.0-alpine
WORKDIR /app
COPY --from=build /app/out .
ENTRYPOINT ["dotnet", "TbspRpgApi.dll"]
