version: '3.3'
services:
#  frontend:
#    build: ./TBSPRPG_UI/tbsprpg
#    ports:
#      - '4200:4200'
#    volumes:
#      - './TBSPRPG_UI/tbsprpg:/app'
#      - /app/node_modules
#    command: ng serve --host 0.0.0.0 --port 4200
#    depends_on:
#      - publicapi

  api:
    build: ./TbspRpg_Monolith
    ports:
      - '8000:8000'
    volumes:
      - './TbspRpg_Monolith/TbspRpgApi:/app'
    environment:
      - 'JwtSettings__Secret=${JWTSECRET}'
      - 'Database__Salt=${DBSALT}'
      - 'CONNECTION_STRING=User ID=${POSTGRESUSER};Password=${POSTGRESPASSWORD};Server=${POSTGRESURL};Port=5432;Database=tbsprpgapi;Integrated Security=true;Pooling=true;'
    command: dotnet watch run
    depends_on: 
      - postgres

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - '8080:80'
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=admin@zorttroz.com'
      - 'PGADMIN_DEFAULT_PASSWORD=admin'
    depends_on:
      - postgres

  postgres:
    image: postgres:13-alpine
    ports:
      - '5432:5432'
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_PASSWORD=tbsprpg'
