name: Digital Ocean Release CI

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version ?'     
        required: true

env:
  CONNECTION_STRING: ${{ secrets.DIGITAL_OCEAN_PROD_DB_CONNECTION_STRING }}
  DATABASE_SALT: ${{ secrets.PROD_DATABASE_SALT }}
  ADMIN_PASSWORD: ${{ secrets.PROD_ADMIN_PASSWORD }}
  TEST_PASSWORD: ${{ secrets.PROD_TEST_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITAL_OCEAN_TOKEN }}
          
    - uses: actions/checkout@v2
    - name: Build and Tag the Docker image
      run: docker build . --file Dockerfile.prod --tag registry.digitalocean.com/tbsprpg/tbsprpgapi:${{ github.event.inputs.version }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Build .NET
      run: dotnet build --configuration Release
    - name: Update Database
      run: |
        dotnet tool install --global dotnet-ef
        dotnet tool restore
        dotnet ef database update -c DatabaseContext -p TbspRpgDataLayer -s TbspRpgDataLayer
      
    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 1200
      
    - name: Push image to DO Container Registry 
      run: docker push registry.digitalocean.com/tbsprpg/tbsprpgapi:${{ github.event.inputs.version }}
